---
- hosts: localhost
  remote_user: root
  tasks:
    - name:  create ops group
      group: name={{ ops_group_name | mandatory }} state=present

    - name: create users
      user: name={{ item.username }} group={{ ops_group_name }}
        groups=sudo state=present shell=/bin/bash
      with_items: sshusers

    - name: allow sudo without password to all members of ops group
      lineinfile: "dest=/etc/sudoers state=present
        regexp='%{{ ops_group_name }} ALL'
        line='%{{ ops_group_name }} ALL=NOPASSWD: ALL'"

    - name: create key directory
      file: path=/etc/ssh/authorized_keys state=directory
        owner=0 group={{ops_group_name}} mode=0750

    - name: upload user keys
      lineinfile: "dest=/etc/ssh/authorised_keys/{{ item.username }}
        state=present
        line='{{ item.ssh_key }}'
        create=yes
        owner={{ item.username }} group=ops mode=640"
      with_items: sshusers

#    - name: download sshd_config template
#      get_url:

    - name: sshd configuration file update
      template: src=../../config/sshd_config.j2
        dest=/etc/ssh/sshd_config
        backup=yes
        owner=0 group=0 mode=0644
        validate='/usr/sbin/sshd -T -f %s'
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      service: name=ssh state=restarted
